version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USERNAME: undistortme
      DB_DATABASE: undistortme
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: undistortme
      POSTGRES_DB: undistortme